ElasticNet:
  alpha: 0.2
  l1_ratio: 0.1

RandomForest:
  n_estimators: 100
  max_depth: 6
  min_samples_split: 2
  random_state: 42

XGBoost:
  n_estimators: 100
  max_depth: 3
  learning_rate: 0.1
  subsample: 1
  random_state: 42